# Generated by Django 5.2.8 on 2025-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='The 32-character key acquired via the CPA network.', max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(help_text='The date and time when the key-based membership expires.')),
                ('cpa_source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Membership Key',
                'verbose_name_plural': 'Membership Keys',
            },
        ),
    ]
