# Generated by Django 5.2.8 on 2025-12-12 11:32

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipkey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Membership Key', 'verbose_name_plural': 'Membership Keys'},
        ),
        migrations.RemoveField(
            model_name='membershipkey',
            name='cpa_source',
        ),
        migrations.AddField(
            model_name='membershipkey',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about key source or user.'),
        ),
        migrations.AddField(
            model_name='membershipkey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to the Django User who owns/used this key.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershipkey',
            name='expiry_date',
            field=models.DateTimeField(default=users.models.get_default_expiry_date),
        ),
        migrations.AlterField(
            model_name='membershipkey',
            name='key',
            field=models.CharField(default=users.models.generate_unique_key, help_text='The 32-character unique membership key.', max_length=32, unique=True),
        ),
    ]
