# Generated by Django 5.2.8 on 2025-12-15 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membershipkey_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(help_text='The user whose active session is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='session_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
