# Generated by Django 5.2.8 on 2025-12-16 08:48

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_avatar_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipkey',
            options={'verbose_name': 'Membership Key', 'verbose_name_plural': 'Membership Keys'},
        ),
        migrations.RemoveField(
            model_name='membershipkey',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='membershipkey',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='The date this key will expire. (Null if not yet activated)', null=True),
        ),
        migrations.AlterField(
            model_name='membershipkey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the key is currently usable for activation/membership. Allows manual deactivation.'),
        ),
        migrations.AlterField(
            model_name='membershipkey',
            name='key',
            field=models.CharField(default=users.models.generate_unique_key, help_text='The unique 32-character key.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipkey',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the key (e.g., source, price, reason for deactivation).'),
        ),
        migrations.AlterField(
            model_name='membershipkey',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The user who activated this key. (Null if unactivated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
