# Generated by Django 5.2.8 on 2025-12-16 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_episodes'),
        ('users', '0006_usercatalogueitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercatalogueitem',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('watchlist', 'Watchlist')], max_length=20),
        ),
        migrations.CreateModel(
            name='MovieVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
