# Generated by Django 5.2.8 on 2025-12-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movies_type'),
        ('movies', '0011_create_directdownloadtoken'),
    ]

    operations = [
    ]
