# Generated by Django 5.2.8 on 2025-12-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_rename_movies_dire_token_idx_movies_dire_token_6de314_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='streamHD_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='streamSD_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
