# Generated by Django 5.2.8 on 2025-12-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movies_streamhd_link_movies_streamsd_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(help_text='The sequence number of the episode (e.g., 1, 2, 3)')),
                ('title', models.CharField(blank=True, help_text="Optional: Title of the episode (e.g., 'The Pilot')", max_length=255, null=True)),
                ('streamSD_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='SD Stream Link (iframe src)')),
                ('streamHD_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='HD Stream Link (iframe src)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['movie', 'episode_number'],
                'unique_together': {('movie', 'episode_number')},
            },
        ),
    ]
