# Generated by Django 5.2.8 on 2025-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this movie page has been viewed.'),
        ),
    ]
